version: '3.9'

services:
  redisdb:
    restart: always
    container_name: redisdb
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    networks:
      - ws-messaging-app
    env_file:
      - .env
    volumes:
      - ./.docker-volumes/redis_volume:/data

  postgresql:
    restart: always
    container_name: postgresql
    image: postgres:alpine
    volumes:
      - ./.docker-volumes/postgres_volume:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ws-messaging-app

  api:
    restart: always
    environment:
      APP_FORK: "false"
      APP_ENV: "production"
      REDIS_URI: "redisdb:6379"
      APP_SELF_CONTAINED: "false"
    build:
      context: .
      dockerfile: docker/nginx-static-setup/api.dockerfile
    env_file: .env
    networks:
      - ws-messaging-app
    depends_on:
      - redisdb
      - postgresql

  proxy:
    restart: always
    container_name: proxy
    build:
      context: .
      dockerfile: docker/nginx-static-setup/nginx.dockerfile
    ports:
      - 8080:8080
    networks:
      - ws-messaging-app
    depends_on:
      - api

networks:
  ws-messaging-app:
    driver: bridge
